### ISSUE TITLE
Missing AdActions

### ISSUE THREAD

**Issue by vforsh** [GameAnalytics/GA-SDK-JAVASCRIPT#141]
There is a discrepancy between [docs for JS SDK](https://gameanalytics.com/docs/item/ad-events/) and [available AdActions](https://github.com/GameAnalytics/GA-SDK-JAVASCRIPT/blob/master/src/Enums.ts#L28)

![image](https://user-images.githubusercontent.com/190223/101454435-09349d80-3942-11eb-946a-f8e9c73a0cf1.png)

I suppose EGAAdAction enum should look like this:

```
    export enum EGAAdAction
    {
        Undefined = 0,
        Clicked = 1,
        Show = 2,
        FailedShow = 3,
        RewardReceived = 4,
        Request = 5,
        Loaded = 6,
    }
```

**Comment by the1schwartz** [comment]
Thanks for letting us know. We have decided to not use "Request" and "Loaded" ad actions currently. The documentation page has just not been updated to reflect this, but it has been done now.
