### ISSUE TITLE
Secret key security vulnerability

### ISSUE THREAD

**Issue by butlimous** [GameAnalytics/GA-SDK-JAVASCRIPT#179]
In the Javascript SDK integration guide at:
https://gameanalytics.com/docs/s/article/Javascript-SDK-Setup

To initialize the SDK and start tracking, the following call should be done:
```
<!-- Traditional way -->
gameanalytics.GameAnalytics.initialize("[game key]", "[secret key]");
<!-- Command queue -->
GameAnalytics("initialize", "[game key]", "[secret key]");
```

The `secret key` is now exposed in javascript in the browser for any hacker to mess with, or am I missing something??

**Comment by the1schwartz** [comment]
The only thing the hacker can do with the secret key is skew the metrics of the game which is hard to see how that would be beneficial to the hacker. We have not had any reported issues regarding this.

**Comment by butlimous** [comment]
Ok. Got it! Thanks very much for clarification :)
