### ISSUE TITLE
Session handling

### ISSUE THREAD

**Issue by helper2424** [GameAnalytics/GA-SDK-JAVASCRIPT#19]
Hi I am migrating my project to your SDK. I have little question. I generate session_id field on server side and send to client side. Previously I setuped this session_id to GA SDK (https://github.com/orange-games/GA-JavaScript-SDK) instance and all events send with this data. In current SDK version I don't see any way to setup session_id

**Comment by cristianbercu** [comment]
Hello, the SDK will assign session IDs automatically. Also, session handling is done automatically in the background. You only need to follow the guidance in the [wiki](https://github.com/GameAnalytics/GA-SDK-JAVASCRIPT/wiki/Download-and-Installation) to [configure](https://github.com/GameAnalytics/GA-SDK-JAVASCRIPT/wiki/Configuration) and [initialise](https://github.com/GameAnalytics/GA-SDK-JAVASCRIPT/wiki/Initializing) the SDK.

Should you have further observations do not hesitate to open a [ticket](http://support.gameanalytics.com/hc/en-us/requests/new) and our support team will quickly get back to you.

**Comment by helper2424** [comment]
Ok, but I need to setup session_id manually. It relate to situation, when events sends from server and client side and need handle all events in one session. How can I setup session_id manually without monkey patching?
