### ISSUE TITLE
Ability to setup custom platform_id

### ISSUE THREAD

**Issue by helper2424** [GameAnalytics/GA-SDK-JAVASCRIPT#20]
Hi, I am using your SDK. GA have problem with custom dimensions, we can't filtering data with it in dashboard. GA support recommend use platform_id like custom dimension. So now we  are using this values like enum and previously setuped platform_id manually. Current version SDK no allow to do this and I don;t wanna use monkey patching, because will happen problems with upgrading SDK. Can you advise something?

**Comment by cristianbercu** [comment]
Hello, I would like to let you know that GA will be rolling out later this year a new backend that will allow you to filter any metric by the custom dimensions you sent over and not only. I suggest to keep on using the custom dimensions (01, 02, 03) and aggregate the data. Once the feature will be out you will be able to use it retroactively. I hope this will be a solution for you.

For any further observations please open a ticket [here](http://support.gameanalytics.com/hc/en-us/requests/new).

**Comment by helper2424** [comment]
Ok, thanks.
