### ISSUE TITLE
Add "typings" field to package.json

### ISSUE THREAD

**Issue by zetorama** [GameAnalytics/GA-SDK-JAVASCRIPT#24]
Hello,

Could you please add ["typings" field](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) to your `package.json`? 

In such case, they'd be auto-imported in typescript projects by using regular `import { GameAnalytics } from 'gameanalytics'`.

Currently I've come up with this work-around: added `global.d.ts` in root directory:
```
/// <reference path="../node_modules/gameanalytics/dist/GameAnalytics.d.ts" />

declare module 'gameanalytics' {
	export = gameanalytics
}
```

Thanks!

**Comment by the1schwartz** [comment]
Thanks for the feedback we will add this to the next release for the SDK

**Comment by the1schwartz** [comment]
"typings" field has now been added in the latest version.
