### ISSUE TITLE
getBrowserVersion string fails on iOS webview

### ISSUE THREAD

**Issue by AleBles** [GameAnalytics/GA-SDK-JAVASCRIPT#27]
Some of our games are loaded through an iOS webview context by external parties.

In this scenario the user agent string doesn't get matched in getBrowserVersion string and causes the succeeding if statements to throw an error.

Here's the UA string in question:

> Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Mobile/15D100

**Comment by the1schwartz** [comment]
Ok thanks for reporting this. We will look into the issue and hopefully making a fix for it in the next relesse of the SDK

**Comment by the1schwartz** [comment]
There should be a fix now in the latest version and it should come as "webkit_ios [IOS_VERSION]" for browser version now. Hope this helps.
