### ISSUE TITLE
Error: Module not found

### ISSUE THREAD

**Issue by walmink** [GameAnalytics/GA-SDK-JAVASCRIPT#37]
I have installed **ga-sdk-javascript** via npm command-line and am importing it into a React project:
```
import * as GA from "ga-javascript-sdk";
```

I get the following error:
```
Module not found: Can't resolve 'ga-javascript-sdk' in
[path to the project file that's loading the module]
```

Any suggestion what I'm missing, or what may be the problem?

**Comment by the1schwartz** [comment]
The 'ga-javascript-sdk' module is not developed by GameAnalytics. Look at https://gameanalytics.com/docs/item/javascript-sdk on how to install the SDK developed by GameAnalytics. The SDK has not been tested in a React project though but let me know if it works for you.
