### ISSUE TITLE
OPTIONS https://api.gameanalytics.com/v2/..../events net::ERR_CONNECTION_REFUSED 

### ISSUE THREAD

**Issue by mohsenyz** [GameAnalytics/GA-SDK-JAVASCRIPT#38]
This is the log of browser while loading the js sdk. I'm from Iran (A banned country). Does it make scene?

**Comment by mohsenyz** [comment]
Oh, Tested with vpn, doesn't make a scene

**Comment by the1schwartz** [comment]
ok i will close this again then
