### ISSUE TITLE
fixMissingSessionEndEvents empty sessions array

### ISSUE THREAD

**Issue by bitmaksim** [GameAnalytics/GA-SDK-JAVASCRIPT#7]
Please fix that issue.
If sessions = Array[0] then if !sessions on true and logic fails.
You could add additional check for sessions.lenght > 0

```
GAEvents.fixMissingSessionEndEvents = function () {
                var args = [];
                args.push(["session_id", EGAStoreArgsOperator.NotEqual, GAState.getSessionId()]);
                var sessions = GAStore.select(EGAStore.Sessions, args);
                if (!sessions) {
                    return;
                }
...
```
if (!sessions **|| sessions.length == 0**) 

Thanks.

**Comment by the1schwartz** [comment]
Thanks for noticing this, but don't you mean if (!sessions **|| sessions.length == 0**) or am I missing something?

**Comment by bitmaksim** [comment]
@the1schwartz you are right... my typo... 
Please *return* if sessions.length is zero.

**Comment by the1schwartz** [comment]
Great thanks again @bitmaksim I have updated the SDK now with the bug you found.
