### ISSUE TITLE
Error in TypeScript

### ISSUE THREAD

**Issue by k4sr4** [GameAnalytics/GA-SDK-JAVASCRIPT#82]
Hey. I directly added `"gameanalytics": "^4.0.9"` in package.json, but I'm getting this error when trying to build and run:

```
node_modules\gameanalytics\dist\GameAnalytics.node.js:1247
        }());
         ^
ReferenceError: navigator is not defined
```

Do you know what the issue is?

**Comment by the1schwartz** [comment]
The SDK will only work in a browser environment. Are you trying to use the SDK outside a browser environment?

**Comment by k4sr4** [comment]
Yes I was trying to use it in our backend server code. So it has to he used in the front end code? Or is there a way I can make this work?

**Comment by the1schwartz** [comment]
It is only meant to be used in frontend code as it is.
